name: Compiles only

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: calcit-lang/setup-cr@0.0.9
        with:
          version: 0.13.27

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn --version

      - name: Install deps
        run: caps --ci && yarn install --immutable

      - name: "validate snapshots"
        run: |
          cr calcit.cirru edit format
          git diff --exit-code -- calcit.cirru
          cr calcit.cirru --check-only
          cr calcit.cirru --entry server --check-only

      - name: "run tests and deprecated API check"
        run: |
          yarn check:unit
          yarn check:deprecated

      - name: "compile to js"
        run: |
          yarn compile-page
          yarn compile-server
          yarn vite build --base=./
