name: Compiles only

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wget
      run: mkdir ci-bin/ && wget -O ci-bin/calcit_runner http://repo.calcit-lang.org/binaries/linux/calcit_runner
    - name: "permission"
      run: chmod +x ci-bin/calcit_runner

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/

    - name: "compiles to js"
      run: >
        ./ci-bin/calcit_runner --emit-js --once
        && ./ci-bin/calcit_runner --emit-js --once --emit-path out-page/ --init-fn ws-edn.page/main! --reload-fn ws-edn.page/reload!
