name: Compiles only

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'

    - uses: calcit-lang/setup-cr@0.0.3
      with:
        version: "0.8.41"

    - name: "compiles to js"
      run: |
        yarn
        yarn compile-page
        yarn compile-server
        yarn vite build
